# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] -quiet

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] -quiet

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/aurora_64b66b_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_gt || ORIG_REF_NAME==aurora_64b66b_0_gt} -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/synth/aurora_64b66b_0_gt_ooc.xdc

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/synth/aurora_64b66b_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_gt || ORIG_REF_NAME==aurora_64b66b_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] -quiet

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] -quiet

# IP: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/aurora_64b66b_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_gt || ORIG_REF_NAME==aurora_64b66b_0_gt} -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_2/aurora_64b66b_0_fifo_gen_slave_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_slave || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_1/aurora_64b66b_0_fifo_gen_master_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_fifo_gen_master || ORIG_REF_NAME==aurora_64b66b_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/synth/aurora_64b66b_0_gt_ooc.xdc

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/ip_0/synth/aurora_64b66b_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0_gt || ORIG_REF_NAME==aurora_64b66b_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
