# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xci
# IP: The module: 'design_1_rst_ps8_0_96M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xci
# IP: The module: 'design_1_rst_ps8_0_96M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
