# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu48dr-ffvg1517-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/bd/design_1/ipshared/abef/hdl
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/ila_0/hdl/verilog
  } {
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/sources_1/bd/design_1/ipshared/abef/hdl
    c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/ila_0/hdl/verilog
  } {
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_xbar_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_auto_ds_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_auto_pc_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_1_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_2_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_3_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_4_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_5_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_6_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_7_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_8_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_axi_gpio_0_9_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_rst_ps8_0_96M_1_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/design_1_zynq_ultra_ps_e_0_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/aurora_64b66b_0_stub.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/ila_0_stub.v
      c:/Research/aurora_64b66b_0_ex/imports/aurora_64b66b_0_cdc_sync_exdes.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_clock_module.v
      c:/Research/aurora_64b66b_0_ex/imports/aurora_64b66b_0_exdes.v
      c:/Research/aurora_64b66b_0_ex/imports/aurora_64b66b_0_frame_check.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_gt_common_wrapper.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_gt_gtye4_common_wrapper.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_support.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_support_reset_logic.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/aurora_64b66b_0_ultrascale_tx_userclk.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.srcs/shared_logic/gtwizard_ultrascale_v1_7_gtye4_common.v
      C:/Users/praga/Downloads/ps_to_aurora_bridge.v
      C:/Users/praga/Downloads/top_ps_aurora_wrapper_cdc.v
      c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/synth/design_1.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/realtime/top_ps_aurora_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top top_ps_aurora_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/.Xil/Vivado-14592-LAPTOP-CH0R4GF2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
