set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0/design_1_xbar_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0/design_1_xbar_0_in_context.xdc id:1 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/ps8_0_axi_periph/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0/design_1_auto_ds_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0/design_1_auto_ds_0_in_context.xdc id:2 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_ds} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0/design_1_auto_pc_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0/design_1_auto_pc_0_in_context.xdc id:3 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_pc} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_in_context.xdc id:4 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_in_context.xdc id:5 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_status} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2/design_1_axi_gpio_0_0_in_context.xdc id:6 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_in_context.xdc id:7 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_ctrl} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4/design_1_axi_gpio_0_0_in_context.xdc id:8 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data7} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5/design_1_axi_gpio_0_0_in_context.xdc id:9 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data6} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6/design_1_axi_gpio_0_0_in_context.xdc id:10 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data5} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7/design_1_axi_gpio_0_0_in_context.xdc id:11 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data4} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_8/design_1_axi_gpio_0_8/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_8/design_1_axi_gpio_0_8/design_1_axi_gpio_0_0_in_context.xdc id:12 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data3} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9/design_1_axi_gpio_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9/design_1_axi_gpio_0_0_in_context.xdc id:13 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/axi_gpio_tx_data2} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_in_context.xdc id:14 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/rst_ps8_0_96M} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc id:15 order:EARLY scoped_inst:u_design_1_wrapper/design_1_i/zynq_ultra_ps_e_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0/aurora_64b66b_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0/aurora_64b66b_0_in_context.xdc id:16 order:EARLY scoped_inst:u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.gen/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc rfile:../../../../../aurora_64b66b_0_ex.gen/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc id:17 order:EARLY scoped_inst:u_aurora_64b66b_0_exdes/u_ila} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/imports/aurora_64b66b_0_exdes.xdc rfile:../../../../../imports/aurora_64b66b_0_exdes.xdc id:18} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/aurora_64b66b_0_ex.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:19} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Research/aurora_64b66b_0_ex/fixed_initclk_force.xdc rfile:../../../../../fixed_initclk_force.xdc id:20 order:LATE} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:21 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:22 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:23 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:24 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl id:25 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl rfile:../../../../../../../Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl id:26 order:LATE scoped_inst:u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/ps8_0_axi_periph/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/xbar]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_ds/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_ds]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_pc/aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_pc]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data0/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_status/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_status]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data1/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data1]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_ctrl/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_ctrl]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data7/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data7]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data6/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data6]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data5/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data5]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data4/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data4]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data3/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data3]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/axi_gpio_tx_data2/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data2]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_design_1_wrapper/design_1_i/rst_ps8_0_96M/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/rst_ps8_0_96M]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name u_design_1_wrapper/design_1_i/zynq_ultra_ps_e_0/pl_clk0 [get_pins u_design_1_wrapper/design_1_i/zynq_ultra_ps_e_0/pl_clk0]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_design_1_wrapper/design_1_i/zynq_ultra_ps_e_0]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/tx_out_clk -source [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/gt_qpllclk_quad1_in] -edges {1 2 3} -edge_shift {0.000 3.007 6.014} [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/tx_out_clk]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXN[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXN[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXN[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXN[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXN[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXN[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXN[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXN[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXP[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXP[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXP[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXP[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXP[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXP[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {RXP[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {RXP[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXN[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXN[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXN[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXN[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXN[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXN[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXN[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXN[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXP[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXP[0]}]
set_property src_info {type:SCOPED_XDC file:16 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXP[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXP[1]}]
set_property src_info {type:SCOPED_XDC file:16 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXP[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXP[2]}]
set_property src_info {type:SCOPED_XDC file:16 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {TXP[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {TXP[3]}]
set_property src_info {type:SCOPED_XDC file:16 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 0.194 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/gt_qpllclk_quad1_in]
set_property src_info {type:SCOPED_XDC file:16 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 6.4 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/gt_qpllrefclk_quad1_in]
set_property src_info {type:SCOPED_XDC file:16 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 6.206 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/init_clk]
set_property src_info {type:SCOPED_XDC file:16 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 6.4 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/refclk1_in]
set_property src_info {type:SCOPED_XDC file:16 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.103 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/sync_clk]
set_property src_info {type:SCOPED_XDC file:16 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.103 [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i/user_clk]
set_property src_info {type:SCOPED_XDC file:16 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_aurora_64b66b_0_exdes/u_ila/clk]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_aurora_64b66b_0_exdes/u_ila]
set_property src_info {type:XDC file:18 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name init_clk_in [get_ports INIT_CLK_P]
set_property src_info {type:XDC file:18 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 6.400 -name gt_refclk1_in [get_ports GTYQ0_P]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {GTYE4_COMMON_QPLL1OUTCLK[0]} -source [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/GTREFCLK01] -multiply_by 33 -add -master_clock [get_clocks gt_refclk1_in] [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/QPLL1OUTCLK]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {GTYE4_COMMON_QPLL1OUTREFCLK[0]} -source [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/GTREFCLK01] -multiply_by 1 -add -master_clock [get_clocks gt_refclk1_in] [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/QPLL1OUTREFCLK]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {GTYE4_COMMON_REFCLKOUTMONITOR1[0]} -source [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/GTREFCLK01] -multiply_by 1 -add -master_clock [get_clocks gt_refclk1_in] [get_pins u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/ultrascale_gt_common_1/aurora_64b66b_0_gt_gtye4_common_wrapper_i/common_inst/gtye4_common_gen.GTYE4_COMMON_PRIM_INST/REFCLKOUTMONITOR1]
set_property src_info {type:XDC file:18 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks init_clk_in -include_generated_clocks] -group [get_clocks gt_refclk1_in -include_generated_clocks]
set_property src_info {type:XDC file:18 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/clock_module_i/ultrascale_tx_userclk_1/gen_gtwiz_userclk_tx_main.tx_active_aurora_64b66b_0_cdc_to_reg/D u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/support_reset_logic_i/u_rst_sync_gt/stg1_aurora_64b66b_0_cdc_to_reg/D u_aurora_64b66b_0_exdes/u_rst_sync_gtrsttmpi/stg1_aurora_64b66b_0_cdc_to_reg/D]]
set_property src_info {type:XDC file:20 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports INIT_CLK_P]
set_property src_info {type:XDC file:20 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports INIT_CLK_N]
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:21 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.208
current_instance
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:22 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.208
current_instance
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:23 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.208
current_instance
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:24 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.208
current_instance
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
current_instance u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_ds]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph/s00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/ps8_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_status]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_ctrl]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data7]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data6]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data5]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data4]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/axi_gpio_tx_data2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/rst_ps8_0_96M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_design_1_wrapper/design_1_i/zynq_ultra_ps_e_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_aurora_64b66b_0_exdes/aurora_64b66b_0_block_i/aurora_64b66b_0_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_aurora_64b66b_0_exdes/u_ila]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ps_to_aurora_bridge/u_ps_to_aurora_fifo]
